### PR TITLE
Add GET /status endpoint

### PR DESCRIPTION
**Pull request by pedropombeiro**
```shell
$http GET http://localhost:5678/status
HTTP/1.0 200 OK
Content-Length: 93
Content-Type: application/json
Date: Sun, 29 Aug 2021 09:10:37 GMT
Server: Werkzeug/2.0.1 Python/3.9.6

{
    "belt_state": "running",
    "dist": 0.0,
    "speed": 0.9,
    "steps": 9,
    "time": 15
}
```

### CODE REVIEW

**Comment by huserben** [comment]
@pedropombeiro 

Thanks for extending the functionality/cleaning up the code and creating Pull Requests so that others can profit as well. This is really cool!

**Comment by pedropombeiro** [comment]
My pleasure. Thanks for accepting the pull requests so quickly!

**Comment by pedropombeiro** [comment]
@huserben Out of curiosity, has `on_new_status` been working for you? It never gets called for me.

**Comment by huserben** [comment]
@pedropombeiro 

Yes for me it's working and I'm using it multiple times a day to store my walk-data in a db.
Are you using the ph4_walkingpad package from pip?

**Comment by pedropombeiro** [comment]
> Are you using the ph4_walkingpad package from pip?

@huserben 

Yes, but I never got it to get called. `handler_last_status` never gets called and `handler_cur_status` only gets called when I call `ask_stats`, which kind of defeats the idea of being event-driven.

**Comment by huserben** [comment]
Yeah `handler_last_status` get's called when you call `ask_hist(0)`.
Can't argue with you on the event driven approach though. Honestly so far i was just happy that it works. Maybe something can be figured out when looking more into the [ph4_walkingpad code](https://github.com/ph4r05/ph4-walkingpad)?

**Comment by pedropombeiro** [comment]
Not a biggie, same thing for me, I'm happy that this much is working. I figure that the issue could be coming from one layer deeper (the Blink library, or maybe even the device's implementation of Bluetooth notifications).

Right now I'm playing with an upgrade to this library which creates a permanent Bluetooth connection to the device so that it basically acts like a gateway and each HTTP request doesn't mean establishing a new connection to the walkingpad. That allows me to integrate it with my Elgato Stream Deck to display step count as well as Home Assistant and Grafana/Prometheus to collect metrics (added a Prometheus client implementation).

2021-09-03 at 15 16

2021-09-03 at 15 16

**Comment by huserben** [comment]
@ettoreferranti would this be interesting for you as well?

**Comment by ettoreferranti** [comment]
Yes, I'm doing exactly this in my (work in progress) library. I have a rest request to connect, and I keep the connection open until I disconnect with another request.

**Comment by ettoreferranti** [comment]
https://github.com/ettoreferranti/walkingpad/blob/main/api.py

**Comment by huserben** [comment]
@pedropombeiro are you planning on pushing some of those changes to the repo (respectively do you have them in one of your repos)? I'd be interested to have a look at it, as I'm currently also using a grafana Dashboard to visualize it, but only after my walk has finished.

**Comment by pedropombeiro** [comment]
@huserben I have my current working state at https://github.com/pedropombeiro/walkingpad/blob/aiohttp/restserver.py, but it is not yet cleaned up. I'm letting any bugs pop up before I clean it up and push it upstream in case you're interested. One thing I did was to allow POST requests to read JSON bodies, so that Home Assistant can also control the walking pad through a REST switch.

**Pull request merged**
